### ISSUE TITLE
Fix the warnings thrown when running the 'is rendered' test in Chess.test.js

### ISSUE THREAD

**Issue by programarivm** [programarivm/redux-chess#58]
Even though the test pass in [`__tests__/components/Chess.test.js`](https://github.com/programarivm/redux-chess/blob/master/src/__tests__/components/Chess.test.js), the following warnings are displayed when running `npm test`

```
 PASS  src/__tests__/utils/Ascii.test.js
 PASS  src/__tests__/utils/Piece.test.js
 PASS  src/__tests__/components/Chess.test.js
  ● Console

    console.error
      Warning: Failed prop type: Invalid prop `variant` of value `text` supplied to `ForwardRef(Menu)`, expected one of ["menu","selectedMenu"].
          at Menu (/home/standard/projects/redux-chess/node_modules/@material-ui/core/Menu/Menu.js:67:32)
          at WithStyles(ForwardRef(Menu)) (/home/standard/projects/redux-chess/node_modules/@material-ui/styles/withStyles/withStyles.js:67:31)
          at div
          at ButtonGroup (/home/standard/projects/redux-chess/node_modules/@material-ui/core/ButtonGroup/ButtonGroup.js:207:24)
          at WithStyles(ForwardRef(ButtonGroup)) (/home/standard/projects/redux-chess/node_modules/@material-ui/styles/withStyles/withStyles.js:67:31)
          at Settings (/home/standard/projects/redux-chess/src/components/Buttons.js:14:20)
          at Provider (/home/standard/projects/redux-chess/node_modules/react-redux/lib/components/Provider.js:21:20)
          at Chess (/home/standard/projects/redux-chess/src/components/Chess.js:12:17)
          at WrapperComponent (/home/standard/projects/redux-chess/node_modules/enzyme-adapter-utils/src/createMountWrapper.jsx:49:26)

      at printWarning (node_modules/react/cjs/react.development.js:220:30)
      at error (node_modules/react/cjs/react.development.js:196:5)
      at checkPropTypes (node_modules/react/cjs/react.development.js:1935:11)
      at validatePropTypes (node_modules/react/cjs/react.development.js:2136:7)
      at Object.createElementWithValidation [as createElement] (node_modules/react/cjs/react.development.js:2240:5)
      at WithStyles(ForwardRef(Menu)) (node_modules/@material-ui/styles/withStyles/withStyles.js:97:42)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14985:18)
      at updateForwardRef (node_modules/react-dom/cjs/react-dom.development.js:17044:20)

    console.error
      Warning: Failed prop type: Invalid prop `variant` of value `text` supplied to `ForwardRef(MenuList)`, expected one of ["menu","selectedMenu"].
          at MenuList (/home/standard/projects/redux-chess/node_modules/@material-ui/core/MenuList/MenuList.js:117:23)
          at Menu (/home/standard/projects/redux-chess/node_modules/@material-ui/core/Menu/Menu.js:67:32)
          at WithStyles(ForwardRef(Menu)) (/home/standard/projects/redux-chess/node_modules/@material-ui/styles/withStyles/withStyles.js:67:31)
          at div
          at ButtonGroup (/home/standard/projects/redux-chess/node_modules/@material-ui/core/ButtonGroup/ButtonGroup.js:207:24)
          at WithStyles(ForwardRef(ButtonGroup)) (/home/standard/projects/redux-chess/node_modules/@material-ui/styles/withStyles/withStyles.js:67:31)
          at Settings (/home/standard/projects/redux-chess/src/components/Buttons.js:14:20)
          at Provider (/home/standard/projects/redux-chess/node_modules/react-redux/lib/components/Provider.js:21:20)
          at Chess (/home/standard/projects/redux-chess/src/components/Chess.js:12:17)
          at WrapperComponent (/home/standard/projects/redux-chess/node_modules/enzyme-adapter-utils/src/createMountWrapper.jsx:49:26)

      at printWarning (node_modules/react/cjs/react.development.js:220:30)
      at error (node_modules/react/cjs/react.development.js:196:5)
      at checkPropTypes (node_modules/react/cjs/react.development.js:1935:11)
      at validatePropTypes (node_modules/react/cjs/react.development.js:2136:7)
      at Object.createElementWithValidation [as createElement] (node_modules/react/cjs/react.development.js:2240:5)
      at Menu (node_modules/@material-ui/core/Menu/Menu.js:182:33)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14985:18)
      at updateForwardRef (node_modules/react-dom/cjs/react-dom.development.js:17044:20)

    console.error
      Warning: Invalid DOM property `tabindex`. Did you mean `tabIndex`?
          at span
          at div
          at div
          at div
          at div
          at Board (/home/standard/projects/redux-chess/src/components/Board.js:13:17)
          at Provider (/home/standard/projects/redux-chess/node_modules/react-redux/lib/components/Provider.js:21:20)
          at Chess (/home/standard/projects/redux-chess/src/components/Chess.js:12:17)
          at WrapperComponent (/home/standard/projects/redux-chess/node_modules/enzyme-adapter-utils/src/createMountWrapper.jsx:49:26)

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at validateProperty$1 (node_modules/react-dom/cjs/react-dom.development.js:3505:9)
      at warnUnknownProperties (node_modules/react-dom/cjs/react-dom.development.js:3559:21)
      at validateProperties$2 (node_modules/react-dom/cjs/react-dom.development.js:3583:3)
      at validatePropertiesInDevelopment (node_modules/react-dom/cjs/react-dom.development.js:8765:5)
      at setInitialProperties (node_modules/react-dom/cjs/react-dom.development.js:9041:5)
      at finalizeInitialChildren (node_modules/react-dom/cjs/react-dom.development.js:10201:3)

    console.error
      Warning: React does not recognize the `disableElevation` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `disableelevation` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
          at div
          at Portal (/home/standard/projects/redux-chess/node_modules/@material-ui/core/Portal/Portal.js:39:24)
          at Modal (/home/standard/projects/redux-chess/node_modules/@material-ui/core/Modal/Modal.js:94:36)
          at Popover (/home/standard/projects/redux-chess/node_modules/@material-ui/core/Popover/Popover.js:118:22)
          at WithStyles(ForwardRef(Popover)) (/home/standard/projects/redux-chess/node_modules/@material-ui/styles/withStyles/withStyles.js:67:31)
          at Menu (/home/standard/projects/redux-chess/node_modules/@material-ui/core/Menu/Menu.js:67:32)
          at WithStyles(ForwardRef(Menu)) (/home/standard/projects/redux-chess/node_modules/@material-ui/styles/withStyles/withStyles.js:67:31)
          at div
          at ButtonGroup (/home/standard/projects/redux-chess/node_modules/@material-ui/core/ButtonGroup/ButtonGroup.js:207:24)
          at WithStyles(ForwardRef(ButtonGroup)) (/home/standard/projects/redux-chess/node_modules/@material-ui/styles/withStyles/withStyles.js:67:31)
          at Settings (/home/standard/projects/redux-chess/src/components/Buttons.js:14:20)
          at Provider (/home/standard/projects/redux-chess/node_modules/react-redux/lib/components/Provider.js:21:20)
          at Chess (/home/standard/projects/redux-chess/src/components/Chess.js:12:17)
          at WrapperComponent (/home/standard/projects/redux-chess/node_modules/enzyme-adapter-utils/src/createMountWrapper.jsx:49:26)

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at validateProperty$1 (node_modules/react-dom/cjs/react-dom.development.js:3513:7)
      at warnUnknownProperties (node_modules/react-dom/cjs/react-dom.development.js:3559:21)
      at validateProperties$2 (node_modules/react-dom/cjs/react-dom.development.js:3583:3)
      at validatePropertiesInDevelopment (node_modules/react-dom/cjs/react-dom.development.js:8765:5)
      at setInitialProperties (node_modules/react-dom/cjs/react-dom.development.js:9041:5)
      at finalizeInitialChildren (node_modules/react-dom/cjs/react-dom.development.js:10201:3)

    console.error
      Warning: React does not recognize the `disableFocusRipple` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `disablefocusripple` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
          at div
          at Portal (/home/standard/projects/redux-chess/node_modules/@material-ui/core/Portal/Portal.js:39:24)
          at Modal (/home/standard/projects/redux-chess/node_modules/@material-ui/core/Modal/Modal.js:94:36)
          at Popover (/home/standard/projects/redux-chess/node_modules/@material-ui/core/Popover/Popover.js:118:22)
          at WithStyles(ForwardRef(Popover)) (/home/standard/projects/redux-chess/node_modules/@material-ui/styles/withStyles/withStyles.js:67:31)
          at Menu (/home/standard/projects/redux-chess/node_modules/@material-ui/core/Menu/Menu.js:67:32)
          at WithStyles(ForwardRef(Menu)) (/home/standard/projects/redux-chess/node_modules/@material-ui/styles/withStyles/withStyles.js:67:31)
          at div
          at ButtonGroup (/home/standard/projects/redux-chess/node_modules/@material-ui/core/ButtonGroup/ButtonGroup.js:207:24)
          at WithStyles(ForwardRef(ButtonGroup)) (/home/standard/projects/redux-chess/node_modules/@material-ui/styles/withStyles/withStyles.js:67:31)
          at Settings (/home/standard/projects/redux-chess/src/components/Buttons.js:14:20)
          at Provider (/home/standard/projects/redux-chess/node_modules/react-redux/lib/components/Provider.js:21:20)
          at Chess (/home/standard/projects/redux-chess/src/components/Chess.js:12:17)
          at WrapperComponent (/home/standard/projects/redux-chess/node_modules/enzyme-adapter-utils/src/createMountWrapper.jsx:49:26)

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at validateProperty$1 (node_modules/react-dom/cjs/react-dom.development.js:3513:7)
      at warnUnknownProperties (node_modules/react-dom/cjs/react-dom.development.js:3559:21)
      at validateProperties$2 (node_modules/react-dom/cjs/react-dom.development.js:3583:3)
      at validatePropertiesInDevelopment (node_modules/react-dom/cjs/react-dom.development.js:8765:5)
      at setInitialProperties (node_modules/react-dom/cjs/react-dom.development.js:9041:5)
      at finalizeInitialChildren (node_modules/react-dom/cjs/react-dom.development.js:10201:3)

    console.error
      Warning: React does not recognize the `disableRipple` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `disableripple` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
          at div
          at Portal (/home/standard/projects/redux-chess/node_modules/@material-ui/core/Portal/Portal.js:39:24)
          at Modal (/home/standard/projects/redux-chess/node_modules/@material-ui/core/Modal/Modal.js:94:36)
          at Popover (/home/standard/projects/redux-chess/node_modules/@material-ui/core/Popover/Popover.js:118:22)
          at WithStyles(ForwardRef(Popover)) (/home/standard/projects/redux-chess/node_modules/@material-ui/styles/withStyles/withStyles.js:67:31)
          at Menu (/home/standard/projects/redux-chess/node_modules/@material-ui/core/Menu/Menu.js:67:32)
          at WithStyles(ForwardRef(Menu)) (/home/standard/projects/redux-chess/node_modules/@material-ui/styles/withStyles/withStyles.js:67:31)
          at div
          at ButtonGroup (/home/standard/projects/redux-chess/node_modules/@material-ui/core/ButtonGroup/ButtonGroup.js:207:24)
          at WithStyles(ForwardRef(ButtonGroup)) (/home/standard/projects/redux-chess/node_modules/@material-ui/styles/withStyles/withStyles.js:67:31)
          at Settings (/home/standard/projects/redux-chess/src/components/Buttons.js:14:20)
          at Provider (/home/standard/projects/redux-chess/node_modules/react-redux/lib/components/Provider.js:21:20)
          at Chess (/home/standard/projects/redux-chess/src/components/Chess.js:12:17)
          at WrapperComponent (/home/standard/projects/redux-chess/node_modules/enzyme-adapter-utils/src/createMountWrapper.jsx:49:26)

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at validateProperty$1 (node_modules/react-dom/cjs/react-dom.development.js:3513:7)
      at warnUnknownProperties (node_modules/react-dom/cjs/react-dom.development.js:3559:21)
      at validateProperties$2 (node_modules/react-dom/cjs/react-dom.development.js:3583:3)
      at validatePropertiesInDevelopment (node_modules/react-dom/cjs/react-dom.development.js:8765:5)
      at setInitialProperties (node_modules/react-dom/cjs/react-dom.development.js:9041:5)
      at finalizeInitialChildren (node_modules/react-dom/cjs/react-dom.development.js:10201:3)

    console.error
      Warning: React does not recognize the `fullWidth` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `fullwidth` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
          at div
          at Portal (/home/standard/projects/redux-chess/node_modules/@material-ui/core/Portal/Portal.js:39:24)
          at Modal (/home/standard/projects/redux-chess/node_modules/@material-ui/core/Modal/Modal.js:94:36)
          at Popover (/home/standard/projects/redux-chess/node_modules/@material-ui/core/Popover/Popover.js:118:22)
          at WithStyles(ForwardRef(Popover)) (/home/standard/projects/redux-chess/node_modules/@material-ui/styles/withStyles/withStyles.js:67:31)
          at Menu (/home/standard/projects/redux-chess/node_modules/@material-ui/core/Menu/Menu.js:67:32)
          at WithStyles(ForwardRef(Menu)) (/home/standard/projects/redux-chess/node_modules/@material-ui/styles/withStyles/withStyles.js:67:31)
          at div
          at ButtonGroup (/home/standard/projects/redux-chess/node_modules/@material-ui/core/ButtonGroup/ButtonGroup.js:207:24)
          at WithStyles(ForwardRef(ButtonGroup)) (/home/standard/projects/redux-chess/node_modules/@material-ui/styles/withStyles/withStyles.js:67:31)
          at Settings (/home/standard/projects/redux-chess/src/components/Buttons.js:14:20)
          at Provider (/home/standard/projects/redux-chess/node_modules/react-redux/lib/components/Provider.js:21:20)
          at Chess (/home/standard/projects/redux-chess/src/components/Chess.js:12:17)
          at WrapperComponent (/home/standard/projects/redux-chess/node_modules/enzyme-adapter-utils/src/createMountWrapper.jsx:49:26)

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at validateProperty$1 (node_modules/react-dom/cjs/react-dom.development.js:3513:7)
      at warnUnknownProperties (node_modules/react-dom/cjs/react-dom.development.js:3559:21)
      at validateProperties$2 (node_modules/react-dom/cjs/react-dom.development.js:3583:3)
      at validatePropertiesInDevelopment (node_modules/react-dom/cjs/react-dom.development.js:8765:5)
      at setInitialProperties (node_modules/react-dom/cjs/react-dom.development.js:9041:5)
      at finalizeInitialChildren (node_modules/react-dom/cjs/react-dom.development.js:10201:3)


Test Suites: 3 passed, 3 total
Tests:       20 passed, 20 total
Snapshots:   0 total
Time:        5.249 s
Ran all test suites.

Watch Usage: Press w to show more.
```

**Comment by programarivm** [comment]
Merged PRs https://github.com/programarivm/redux-chess/pull/67 and https://github.com/programarivm/redux-chess/pull/68
